// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/8/2024, 2:47:04 PM
const configMerger = require("/Users/khosroheidari/Desktop/todo-app/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/khosroheidari/Desktop/todo-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/khosroheidari/Desktop/todo-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/khosroheidari/Desktop/todo-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/khosroheidari/Desktop/todo-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/khosroheidari/Desktop/todo-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/khosroheidari/Desktop/todo-app/plugins/**/*.{js,ts,mjs}","/Users/khosroheidari/Desktop/todo-app/composables/**/*.{js,ts,mjs}","/Users/khosroheidari/Desktop/todo-app/utils/**/*.{js,ts,mjs}","/Users/khosroheidari/Desktop/todo-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/khosroheidari/Desktop/todo-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/khosroheidari/Desktop/todo-app/app.config.{js,ts,mjs}"] }));

module.exports = config
